<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit7de4645e1fb809c23ff4ee598ec3a2c6
{
    public static $prefixLengthsPsr4 = array (
        'S' => 
        array (
            'ShinyBaseWeb\\' => 13,
        ),
        'Q' => 
        array (
            'QeyWork\\' => 8,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'ShinyBaseWeb\\' => 
        array (
            0 => __DIR__ . '/../..' . '/web',
        ),
        'QeyWork\\' => 
        array (
            0 => __DIR__ . '/../..' . '/qeyWork',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit7de4645e1fb809c23ff4ee598ec3a2c6::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit7de4645e1fb809c23ff4ee598ec3a2c6::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
